// [AsmJit]
// Complete x86/x64 JIT and Remote Assembler for C++.
//
// [License]
// Zlib - See LICENSE.md file in the package.

// This file is used to test opcodes generated by AsmJit. Output can be
// disassembled in your IDE or by your favourite disassembler. Instructions
// are grouped by category and then sorted alphabetically.

// [Dependencies - AsmJit]
#include <asmjit/asmjit.h>

// [Dependencies - Test]
#include "genopcode.h"

// [Dependencies - C]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef void (*VoidFunc)(void);

int main(int argc, char* argv[]) {
  using namespace asmjit;
  using namespace asmjit::host;

  FileLogger logger(stdout);
  logger.setOption(kLoggerOptionBinaryForm, true);

  JitRuntime runtime;
  X86Assembler a(&runtime);

  a.setLogger(&logger);
  asmgen::opcode(a);

  VoidFunc p = asmjit_cast<VoidFunc>(a.make());
  p();
  runtime.release((void*)p);

  return 0;
}
